# a big list of all countries just for use if necessary

ALL_COUNTRIES = [
('INVALID', '--------'),
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctica'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvet Island'),
('BR', 'Brazil'),
('IO', 'British Indian Ocean Territory'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CV', 'Cape Verde'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CD', 'Congo, The Democratic Republic of the'),
('CK', 'Cook Islands'),
('CR', 'Costa Rica'),
('CI', 'Cote D\'Ivoire'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Ethiopia'),
('FK', 'Falkland Islands (Malvinas)'),
('FO', 'Faroe Islands'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('TF', 'French Southern Territories'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HM', 'Heard Island and McDonald Islands'),
('VA', 'Holy See (Vatican City State)'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran, Islamic Republic of'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', 'Korea, Democratic People\'s Republic of'),
('KR', 'Korea, Republic of'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', 'Lao People\'s Democratic Republic'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libyan Arab Jamahiriya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macedonia, The Former Yugoslav Republic of'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia, Federated States of'),
('MD', 'Moldova, Republic of'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('AN', 'Netherlands Antilles'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestinian Territory, Occupied'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PN', 'Pitcairn'),
('PL', 'Poland'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('RE', 'Reunion'),
('RO', 'Romania'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('BL', 'Saint Barthelemy'),
('SH', 'Saint Helena'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin'),
('PM', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and the Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('GS', 'South Georgia and the South Sandwich Islands'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SJ', 'Svalbard and Jan Mayen'),
('SZ', 'Swaziland'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan, Province Of China'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania, United Republic of'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TC', 'Turks and Caicos Islands'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UM', 'United States Minor Outlying Islands'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Viet Nam'),
('VG', 'Virgin Islands, British'),
('VI', 'Virgin Islands, U.S.'),
('WF', 'Wallis And Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe'),
]

# EUROPE, UK and AMERICA
UNITED_STATES = 'US'
INVALID = '--'
AUSTRIA = 'AT'
BELGIUM = 'BE'
BULGARIA = 'BG'
CANADA = 'CA'
CYPRUS = 'CY'
CZECH_REPUBLIC = 'CZ'
DENMARK = 'DK'
ESTONIA = 'EE'
FINLAND = 'FI'
FRANCE = 'FR'  
GERMANY = 'DE' 
GREECE = 'GR' 
HUNGARY = 'HU'
IRELAND = 'IE'  
ITALY = 'IT' 
LATVIA = 'LV'
LITHUANIA = 'LT'
LUXEMBOURG = 'LU'  
MALTA = 'MT'
NETHERLANDS = 'NL'
NORWAY = 'NO'
POLAND = 'PL'
PORTUGAL = 'PT' 
ROMANIA = 'RO'
SLOVAK_REPUBLIC = 'SK'
SLOVENIA = 'SI'
SPAIN = 'ES'
SWEDEN = 'SE'
SWITZERLAND = 'CH'
UNITED_KINGDOM = 'UK'
UK_EU_US_CA = (
    (UNITED_STATES, u"USA"),
    (INVALID, u"-----"),
    (AUSTRIA, u"Austria"),
    (BELGIUM, u"Belgium"),
    (BULGARIA, u"Bulgaria"),
    (CANADA, u"Canada"),
    (CYPRUS, u"Cyprus"),
    (CZECH_REPUBLIC, u"Czech Republic"),
    (DENMARK, u"Denmark"),
    (ESTONIA, u"Estonia"),
    (FINLAND, u"Finland"),
    (FRANCE, u"France"),
    (GERMANY, u"Germany"), 
    (GREECE, u"Greece"), 
    (HUNGARY, u"Hungary"),
    (IRELAND, u"Ireland"),  
    (ITALY, u"Italy"), 
    (LATVIA, u"Latvia"),
    (LITHUANIA, u"Lithuania"),
    (LUXEMBOURG, u"Luxembourg"),  
    (MALTA, u"Malta"),
    (NETHERLANDS, u"Netherlands"),
    (NORWAY, u"Norway"),
    (POLAND, u"Poland"),
    (PORTUGAL, u"Portugal"),
    (ROMANIA, u"Romania"),
    (SLOVAK_REPUBLIC, u"Slovak Republic"),
    (SLOVENIA, u"Slovenia"),
    (SPAIN, u"Spain"),
    (SWEDEN, u"Sweden"),
    (SWITZERLAND, u"Switzerland"),  
    (UNITED_KINGDOM, u"United Kingdom"),   
)

# NORTH AMERICA
UNITED_STATES = 'US'
CANADA = 'CA'
NORTH_AMERICA = (
    (UNITED_STATES, u"USA"),
    (CANADA, u'Canada'),
)

# these are the states in America
US_STATES = (
  (u'AL', u'Alabama'),
  (u'AK', u'Alaska'),
  (u'AZ', u'Arizona'),
  (u'AK', u'Arkansas'),
  (u'CA', u'California'),
  (u'CO', u'Colorado'),
  (u'CT', u'Connecticut'),
  (u'DE', u'Delaware'),
  (u'DC', u'Dist. of Columbia'),
  (u'FL', u'Florida'),
  (u'GA', u'Georgia'),
  (u'HI', u'Hawaii'),
  (u'ID', u'Idaho'),
  (u'IL', u'Illinois'),
  (u'IN', u'Indiana'),
  (u'IA', u'Iowa'),
  (u'KS', u'Kansas'),
  (u'KY', u'Kentucky'),
  (u'LA', u'Louisiana'),
  (u'ME', u'Maine'),
  (u'MD', u'Maryland'),
  (u'MA', u'Massachusetts'),
  (u'MI', u'Michigan'),
  (u'MN', u'Minnesota'),
  (u'MS', u'Mississippi'),
  (u'MO', u'Missouri'),
  (u'MT', u'Montana'),
  (u'NE', u'Nebraska'),
  (u'NV', u'Nevada'),
  (u'NH', u'New Hampshire'),
  (u'NJ', u'New Jersey'),
  (u'NM', u'New Mexico'),
  (u'NY', u'New York'),
  (u'NC', u'North Carolina'),
  (u'ND', u'North Dakota'),
  (u'OH', u'Ohio'),
  (u'OK', u'Oklahoma'),
  (u'OR', u'Oregon'),
  (u'PA', u'Pennsylvania'),
  (u'RI', u'Rhode Island'),
  (u'SC', u'South Carolina'),
  (u'South Dakota', u'SD'),
  (u'TN', u'Tennessee'),
  (u'TX', u'Texas'),
  (u'UT', u'Utah'),
  (u'VT', u'Vermont'),
  (u'VA', u'Virginia'),
  (u'WA', u'Washington'),
  (u'WV', u'West Virginia'),
  (u'WI', u'Wisconsin'),
  (u'WY', u'Wyoming'),
)


EUROPE = ('AT', 'BE', 'BG', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT',
    'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH')


